channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pytorch
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - tensorflow
  - torchvision